/**
 * buildInline.js
 * Generates assets/data/dictionary-inline.js
 * Embeds dictionary data as JS for file:// double-click support
 * (fetch() is blocked on file:// but script tags are not)
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const dict = JSON.parse(fs.readFileSync(path.join(ROOT, "assets/data/dictionary-final.json"), "utf8"));
const index = JSON.parse(fs.readFileSync(path.join(ROOT, "assets/data/dictionary-index.json"), "utf8"));

const out = `// Auto-generated by tools/buildInline.js — DO NOT EDIT
// Embedded dictionary data for offline file:// support
window.__DICT_INLINE = {
    dictionary: ${JSON.stringify(dict)},
    index: ${JSON.stringify(index)}
};
`;

fs.writeFileSync(path.join(ROOT, "assets/data/dictionary-inline.js"), out);
console.log(`Generated dictionary-inline.js: ${(out.length / 1024 / 1024).toFixed(1)} MB (${dict.length} words, ${index.length} index entries)`);
